"""add_gis_layer_semantics

Revision ID: ae6574f2c234
Revises: e787a54cb4bc
Create Date: 2026-10-04 18:20:56.649542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ae6574f2c234'
down_revision: Union[str, None] = 'e787a54cb4bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gis_layer_semantics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('layer_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('subcategory', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('semantic_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['layer_id'], ['gis_layers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('layer_id')
    )
    op.create_index('ix_layer_semantics_ai_enabled', 'gis_layer_semantics', ['ai_enabled'], unique=False)
    op.create_index('ix_layer_semantics_category', 'gis_layer_semantics', ['category'], unique=False)
    op.create_index('ix_layer_semantics_layer_id', 'gis_layer_semantics', ['layer_id'], unique=False)
    op.create_index('ix_layer_semantics_subcategory', 'gis_layer_semantics', ['subcategory'], unique=False)
    op.alter_column('gis_datasets', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('gis_datasets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('gis_datasets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_gis_datasets_status', table_name='gis_datasets')
    op.drop_index('idx_gis_datasets_user_id', table_name='gis_datasets')
    op.drop_index('idx_gis_features_layer_id', table_name='gis_features')
    op.alter_column('gis_layers', 'feature_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('gis_layers', 'is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('gis_layers', 'layer_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('gis_layers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('gis_layers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_gis_layers_dataset_id', table_name='gis_layers')
    op.drop_index('idx_gis_layers_layer_order', table_name='gis_layers')
    op.drop_index('ix_workspace_invitations_token', table_name='workspace_invitations')
    op.create_index('ix_workspace_invitations_token', 'workspace_invitations', ['token'], unique=False)
    op.drop_index('ix_workspaces_slug', table_name='workspaces')
    op.create_index('ix_workspaces_slug', 'workspaces', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workspaces_slug', table_name='workspaces')
    op.create_index('ix_workspaces_slug', 'workspaces', ['slug'], unique=True)
    op.drop_index('ix_workspace_invitations_token', table_name='workspace_invitations')
    op.create_index('ix_workspace_invitations_token', 'workspace_invitations', ['token'], unique=True)
    op.create_index('idx_gis_layers_layer_order', 'gis_layers', ['layer_order'], unique=False)
    op.create_index('idx_gis_layers_dataset_id', 'gis_layers', ['dataset_id'], unique=False)
    op.alter_column('gis_layers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('gis_layers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('gis_layers', 'layer_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('gis_layers', 'is_visible',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('gis_layers', 'feature_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index('idx_gis_features_layer_id', 'gis_features', ['layer_id'], unique=False)
    op.create_index('idx_gis_datasets_user_id', 'gis_datasets', ['user_id'], unique=False)
    op.create_index('idx_gis_datasets_status', 'gis_datasets', ['status'], unique=False)
    op.alter_column('gis_datasets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('gis_datasets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('gis_datasets', 'is_public',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('ix_layer_semantics_subcategory', table_name='gis_layer_semantics')
    op.drop_index('ix_layer_semantics_layer_id', table_name='gis_layer_semantics')
    op.drop_index('ix_layer_semantics_category', table_name='gis_layer_semantics')
    op.drop_index('ix_layer_semantics_ai_enabled', table_name='gis_layer_semantics')
    op.drop_table('gis_layer_semantics')
    # ### end Alembic commands ###
